export type HospitalListItem = {
  id: string;
  name: string;
  department: string;
  hours: string;
  distance: string;
  reviewCount: string;
  distanceText: string;
  wait: string;
  waitTime: string;
  price: string;
  consultationFee: string;
  medicinePrice: string;
  totalPrice: string;
  saving: string;
  revisitRate: string;
  image: string;
  address: string;
};

export const hospitalList: HospitalListItem[] = [
  {
    id: "asan-immune-plus",
    name: "아산이문플러스의원",
    department: "내과 · 비만클리닉",
    hours: "영업 중 · 17:30까지",
    distance: "(리뷰 999+) · 2 km",
    reviewCount: "리뷰 999+",
    distanceText: "2 km",
    wait: "평균 대기 10분",
    waitTime: "평균 대기 10분",
    price: "315,000원",
    consultationFee: "29,000원",
    medicinePrice: "286,000원",
    totalPrice: "315,000원",
    saving: "재진 95%",
    revisitRate: "95%",
    image: "/assets/images/hospitals/hospital-list-01.png",
    address: "서울 강남구 테헤란로 123",
  },
  {
    id: "suwon-the-cell",
    name: "수원더셀의원",
    department: "가정의학과 · 비만클리닉",
    hours: "영업 중 · 19:00까지",
    distance: "(리뷰 648) · 3 km",
    reviewCount: "리뷰 648",
    distanceText: "3 km",
    wait: "평균 대기 15분",
    waitTime: "평균 대기 15분",
    price: "300,000원",
    consultationFee: "29,000원",
    medicinePrice: "271,000원",
    totalPrice: "300,000원",
    saving: "재진 92%",
    revisitRate: "92%",
    image: "/assets/images/hospitals/hospital-list-02.png",
    address: "경기 수원시 팔달구 권광로 210",
  },
  {
    id: "hangaon-oriental",
    name: "한가온한방병원",
    department: "한방내과 · 비만클리닉",
    hours: "(금) 09:00 시작",
    distance: "(리뷰 148) · 5 km",
    reviewCount: "리뷰 148",
    distanceText: "5 km",
    wait: "평균 대기 10분",
    waitTime: "평균 대기 10분",
    price: "325,000원",
    consultationFee: "29,000원",
    medicinePrice: "296,000원",
    totalPrice: "325,000원",
    saving: "재진 90%",
    revisitRate: "90%",
    image: "/assets/images/hospitals/hospital-list-03.png",
    address: "서울 서초구 서초대로 77",
  },
  {
    id: "gangnam-bareun",
    name: "강남바른의원",
    department: "내과 · 비만클리닉",
    hours: "영업 중 · 18:30까지",
    distance: "(리뷰 587) · 3 km",
    reviewCount: "리뷰 587",
    distanceText: "3 km",
    wait: "평균 대기 15분",
    waitTime: "평균 대기 15분",
    price: "310,000원",
    consultationFee: "29,000원",
    medicinePrice: "281,000원",
    totalPrice: "310,000원",
    saving: "재진 90%",
    revisitRate: "90%",
    image: "/assets/images/hospitals/hospital-list-04.png",
    address: "서울 강남구 강남대로 402",
  },
  {
    id: "seoul-slim",
    name: "서울슬림의원",
    department: "가정의학과 · 비만클리닉",
    hours: "영업 중 · 20:00까지",
    distance: "(리뷰 332) · 6 km",
    reviewCount: "리뷰 332",
    distanceText: "6 km",
    wait: "평균 대기 20분",
    waitTime: "평균 대기 20분",
    price: "320,000원",
    consultationFee: "29,000원",
    medicinePrice: "291,000원",
    totalPrice: "320,000원",
    saving: "재진 90%",
    revisitRate: "90%",
    image: "/assets/images/hospitals/hospital-list-05.png",
    address: "서울 송파구 올림픽로 300",
  },
  {
    id: "yeoksam-diet-clinic",
    name: "역삼다이어트의원",
    department: "내과 · 체중관리",
    hours: "영업 중 · 18:00까지",
    distance: "(리뷰 721) · 1 km",
    reviewCount: "리뷰 721",
    distanceText: "1 km",
    wait: "평균 대기 8분",
    waitTime: "평균 대기 8분",
    price: "298,000원",
    consultationFee: "28,000원",
    medicinePrice: "270,000원",
    totalPrice: "298,000원",
    saving: "재진 96%",
    revisitRate: "96%",
    image: "/assets/images/thumbnails/hospital-rank-01.png",
    address: "서울 강남구 논현로 508",
  },
  {
    id: "seocho-fit-clinic",
    name: "서초핏의원",
    department: "가정의학과 · 비만클리닉",
    hours: "영업 중 · 19:30까지",
    distance: "(리뷰 412) · 4 km",
    reviewCount: "리뷰 412",
    distanceText: "4 km",
    wait: "평균 대기 12분",
    waitTime: "평균 대기 12분",
    price: "305,000원",
    consultationFee: "27,000원",
    medicinePrice: "278,000원",
    totalPrice: "305,000원",
    saving: "재진 91%",
    revisitRate: "91%",
    image: "/assets/images/thumbnails/hospital-rank-02.png",
    address: "서울 서초구 강남대로 321",
  },
  {
    id: "jamsil-wellness",
    name: "잠실웰니스의원",
    department: "내과 · 대사관리",
    hours: "영업 중 · 20:30까지",
    distance: "(리뷰 286) · 7 km",
    reviewCount: "리뷰 286",
    distanceText: "7 km",
    wait: "평균 대기 18분",
    waitTime: "평균 대기 18분",
    price: "318,000원",
    consultationFee: "30,000원",
    medicinePrice: "288,000원",
    totalPrice: "318,000원",
    saving: "재진 89%",
    revisitRate: "89%",
    image: "/assets/images/thumbnails/hospital-rank-03.png",
    address: "서울 송파구 백제고분로 184",
  },
  {
    id: "pangyo-slim-care",
    name: "판교슬림케어의원",
    department: "가정의학과 · 체중관리",
    hours: "영업 중 · 18:20까지",
    distance: "(리뷰 534) · 9 km",
    reviewCount: "리뷰 534",
    distanceText: "9 km",
    wait: "평균 대기 13분",
    waitTime: "평균 대기 13분",
    price: "307,000원",
    consultationFee: "29,000원",
    medicinePrice: "278,000원",
    totalPrice: "307,000원",
    saving: "재진 93%",
    revisitRate: "93%",
    image: "/assets/images/hospitals/hospital-list-01.png",
    address: "경기 성남시 분당구 판교역로 152",
  },
  {
    id: "bundang-one-clinic",
    name: "분당원클리닉",
    department: "내과 · 비만상담",
    hours: "영업 중 · 17:50까지",
    distance: "(리뷰 205) · 11 km",
    reviewCount: "리뷰 205",
    distanceText: "11 km",
    wait: "평균 대기 6분",
    waitTime: "평균 대기 6분",
    price: "292,000원",
    consultationFee: "26,000원",
    medicinePrice: "266,000원",
    totalPrice: "292,000원",
    saving: "재진 94%",
    revisitRate: "94%",
    image: "/assets/images/hospitals/hospital-list-02.png",
    address: "경기 성남시 분당구 정자일로 95",
  },
  {
    id: "songpa-diet-medical",
    name: "송파다이어트메디컬",
    department: "내과 · 비만클리닉",
    hours: "(금) 10:00 시작",
    distance: "(리뷰 167) · 8 km",
    reviewCount: "리뷰 167",
    distanceText: "8 km",
    wait: "평균 대기 22분",
    waitTime: "평균 대기 22분",
    price: "330,000원",
    consultationFee: "31,000원",
    medicinePrice: "299,000원",
    totalPrice: "330,000원",
    saving: "재진 87%",
    revisitRate: "87%",
    image: "/assets/images/hospitals/hospital-list-03.png",
    address: "서울 송파구 송파대로 345",
  },
  {
    id: "guro-fit-family",
    name: "구로핏패밀리의원",
    department: "가정의학과 · 만성질환관리",
    hours: "영업 중 · 18:40까지",
    distance: "(리뷰 359) · 14 km",
    reviewCount: "리뷰 359",
    distanceText: "14 km",
    wait: "평균 대기 16분",
    waitTime: "평균 대기 16분",
    price: "312,000원",
    consultationFee: "28,000원",
    medicinePrice: "284,000원",
    totalPrice: "312,000원",
    saving: "재진 88%",
    revisitRate: "88%",
    image: "/assets/images/hospitals/hospital-list-04.png",
    address: "서울 구로구 디지털로 272",
  },
  {
    id: "mapo-light-clinic",
    name: "마포라이트의원",
    department: "내과 · 체중관리",
    hours: "영업 중 · 21:00까지",
    distance: "(리뷰 804) · 10 km",
    reviewCount: "리뷰 804",
    distanceText: "10 km",
    wait: "평균 대기 25분",
    waitTime: "평균 대기 25분",
    price: "299,000원",
    consultationFee: "29,000원",
    medicinePrice: "270,000원",
    totalPrice: "299,000원",
    saving: "재진 97%",
    revisitRate: "97%",
    image: "/assets/images/hospitals/hospital-list-05.png",
    address: "서울 마포구 양화로 45",
  },
  {
    id: "yongsan-balance",
    name: "용산밸런스의원",
    department: "가정의학과 · 비만상담",
    hours: "영업 중 · 19:10까지",
    distance: "(리뷰 243) · 12 km",
    reviewCount: "리뷰 243",
    distanceText: "12 km",
    wait: "평균 대기 9분",
    waitTime: "평균 대기 9분",
    price: "322,000원",
    consultationFee: "30,000원",
    medicinePrice: "292,000원",
    totalPrice: "322,000원",
    saving: "재진 86%",
    revisitRate: "86%",
    image: "/assets/images/thumbnails/hospital-rank-01.png",
    address: "서울 용산구 한강대로 95",
  },
];
